#title: Nicholas Mutsaerts
logo: /images/headshot_circle.png
description: IT Support Specialist | Microsoft 365 Administration | Microsoft Intune | Endpoint & Identity Management | Windows & macOS Support | End-User Training | Linux Enthausiast

#description: Theme
theme: jekyll-theme-cayman
show_downloads: false

# GitHub settings
github:
  is_project_page: false
