#title: Nicholas Mutsaerts
logo: /images/headshot_circle.png
description: IT Support Specialist | Microsoft 365, Entra ID & Intune Administrator | Endpoint & Identity Management | Windows & macOS Support

#description: Theme
theme: jekyll-theme-cayman
show_downloads: false

# GitHub settings
github:
  is_project_page: false
